name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  
  build:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t dorianeperlise/portfolio .
      - name: Push image
        run: |
             docker login -u dorianeperlise -p ${{secrets.REGISTRY_PASS}}
             docker push dorianeperlise/portfolio